#!/bin/sh
#
## Example BIRD configuration
#
# define hook_script "scripts/hook/bird-example"
#
# protocol bgp testsession1 {
#	 ...
#    hook established enter hook_script;
#    hook established leave hook_script;
#    hook openconfirm enter hook_script;
#    hook close enter hook_script;
#    hook idle enter hook_script;
#    hook start hook_script;
#    hook shutdown hook_script;
#    hook neighbor grest hook_script;
#    hook conn inbound hook_script;
#    hook conn outbound hook_script;
#    ...
# }
#

. `dirname ${0}`/../common
. `dirname ${0}`/routectl

log()
{
	logger -p local0.notice -t $0[$$] ${@}
	echo ${@}
}

case ${BGP_EVENT} in
	"BGP_HOOK_ENTER_ESTABLISHED")
		log ${PROTO_NAME}: entered established state ${CONN_STATE}
		route_add ${TABLE_NAME} 1.0.0.0/24 && _exit $BGP_HOOK_STATUS_RECONFIGURE
	;;
	"BGP_HOOK_LEAVE_ESTABLISHED")
		log ${PROTO_NAME}: left established state ${CONN_STATE}		
		route_remove ${TABLE_NAME} 1.0.0.0/24 && _exit $BGP_HOOK_STATUS_RECONFIGURE
	;;
	"BGP_HOOK_ENTER_CLOSE")
		log ${PROTO_NAME}: entered closed state		
	;;
	"BGP_HOOK_ENTER_IDLE")
		log ${PROTO_NAME}: entered idle state
	;;
	"BGP_HOOK_ENTER_OPENCONFIRM")
		log ${PROTO_NAME}: entered openconfirm state
	;;
	"BGP_HOOK_SHUTDOWN")
		log ${PROTO_NAME}: shutdown ${DOWN_CODE}
	;;
	"BGP_HOOK_START")
		log ${PROTO_NAME}: start ${START_STATE}
		route_remove ${TABLE_NAME} 1.0.0.0/24 && _exit $BGP_HOOK_STATUS_RECONFIGURE
	;;
	"BGP_HOOK_CONN_INBOUND")
		log ${PROTO_NAME}: inbound connection from ${REMOTE_IP}
	;;
	"BGP_HOOK_CONN_OUTBOUND")
		log ${PROTO_NAME}: outbound connection to ${REMOTE_IP}
	;;	
	BGP_*)
		log ${BGP_EVENT} occured on ${PROTO_NAME} ${CONN_STATE}
	;;
esac

_exit 0
