#!/bin/sh

assemble_rtag() 
{ 
	echo "r_${1}"
}

remove_route_entry()
{
	sed -ri "/route `echo "${2}" | sed -r 's/\//\\\\\//'` reject;/d" "${VARP}/${1}"
}

insert_route_entry()
{
	remove_route_entry ${1} "${2}"
	sed -i "s/}/route `echo "${2}" | sed -r 's/\//\\\\\//'` reject;\n}/" "${VARP}/${1}"
}

# table, prefix
route_add()
{
	rtag=`assemble_rtag ${1}`
	pfix="${2}"
	rp="${VARP}/${rtag}"

	if [ -f ${rp} ]; then
		insert_route_entry ${rtag} "${2}"
	else
		echo "protocol static { 
table ${1}; 
route ${2} reject; 
}" 		> "${VARP}/${rtag}"		
	fi
	insert_config_chunk "${rtag}"
}

route_remove()
{
	rtag=`assemble_rtag ${1}`
	[ -f "${VARP}/${rtag}" ] || return
	remove_route_entry ${rtag} "${2}"	
	cat "${VARP}/${rtag}" | egrep -q "^route [0-9]" || remove_config_chunk ${rtag}
}
